name: PHP CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Validar sintaxis PHP
        run: find . -name "*.php" -exec php -l {} \;
